### ISSUE TITLE
不要import ’react‘

### ISSUE THREAD

**Issue by shijistar** [javaLuo/react-vcode#1]
请不要在页面顶部添加这一行指令：
```js
import React from 'react';
```
否则当外部项目引用index.js时，会再把你的项目里的React库再打包一次。请参考https://github.com/react-bootstrap/react-bootstrap

**Comment by javaLuo** [comment]
@shijistar 
可能有点误会，我没有把编译后的文件上传到github，sorry。
您所看到的index.js是源代码。在webpack build的时候已经排除了react依赖。
在webpack.build.config.js中配置了如下代码：

externals: {
        'react': 'react',
        'react-dom': 'react-dom'
      },

不知道您指的是否是这个问题呢

**Comment by shijistar** [comment]
您回答的很准确。我在config里添加externals就好了，多谢！
