### ISSUE TITLE
在nextjs中报错

### ISSUE THREAD

**Issue by zhouyec** [javaLuo/react-vcode#10]
Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
external%20%22react-vcode%22 (1:0) @ Object.react-vcode

> 1 | module.exports = require("react-vcode");
Call Stack
__webpack_require__
webpack\bootstrap (21:0)
__webpack_require__
webpack\bootstrap (21:0)
<unknown>
webpack\bootstrap (89:0)
Show collapsed frames

**Comment by javaLuo** [comment]
刚发布了1.0.10，再试试看

**Comment by zhouyec** [comment]
react-dom.development.js:88 Warning: Prop `id` did not match. Server: "1599725479928_0.3937" Client: "1599725481057_0.0703"
大佬可以了，但刷新页面，验证码就变成空白的不再显示，onChange是有返值的

**Comment by zhouyec** [comment]
存在width<150，验证码显示不全的问题

**Comment by javaLuo** [comment]
next里使用，加个id吧，不加的话内部会随机分配id，导致和服务端不一致
```
<Vcode id="vcode1" />
```
确实会有显示不全的情况，因为字体旋转后可能转到外面去了，我下个版本优化一下

**Comment by zhouyec** [comment]
有解决吗我看了下最新的，还是存在这个问题

**Comment by javaLuo** [comment]
- - 没有，让我想想怎么搞

**Comment by zhouyec** [comment]
试了下可以设置className css width>props.width ，调整width,让字符完全显示
  <Vcode
                  id="vcode"
                  width={80}
                  className={styles.vcode}
                  onChange={handleClick}
                />

**Comment by javaLuo** [comment]
不会吧，生效的应该是props.width
我之后会把文字出现的位置往中间聚一聚
不过如果整体宽度设置得太小，还是会有超出去的风险

**Comment by zhouyec** [comment]
是的，在不改包的情况下可以正常使用，是样式满足其显示
