### ISSUE TITLE
直接把代码放在 client side 是否会产生安全问题？

### ISSUE THREAD

**Issue by yun-li** [javaLuo/react-vcode#4]
目前的 code 都是 client side，hacker 是不是可以通过源代码直接破解啊？

**Comment by javaLuo** [comment]
对，是纯前端的代码。可以开启webpack的压缩混淆增加破解难度。
实在不放心的话，提供了value属性，可以从后台获取验证码值再显示

**Comment by yun-li** [comment]
如果从后台直接发送 value 的话，是不是也不太安全？不知道能不能在后台生成 图片 然后发送过来

**Comment by javaLuo** [comment]
额 目前不支持。
我稍后做一下这个功能

**Comment by javaLuo** [comment]
发布了1.0.0
* 现在value属性支持 网络图片路径/import本地图片/base64图片码
* 网络图片支持png/jpg/jpeg/gif/bmp/webp
* 图片CSS将被自动设置display:block; max-width:100%; max-height:100%;
* 增加了onClick回调函数
* 需要React16+

**Comment by yun-li** [comment]
非常感谢你的修改帮助。

目前的 code 是会产生一个 html code，从而显示出来。如果在 后端用这样的代码，生成 html code，然后 传送到前端的话可能还是比较容易破解。不知道有没有什么方法可以利用目前的 module， 然后把 html code 转换成图片再传送到前端。

**Comment by javaLuo** [comment]
你的服务端用的Node.js吗，我只知道1个前端的解决方案：
html2canvas https://github.com/niklasvh/html2canvas
服务端的我了解得比较少了...
我搜索了一下github，没发现好一点的Node端html转img的插件

**Comment by yun-li** [comment]
对的 后端用的是 node。不过还是非常感谢你的帮助 :)
