### ISSUE TITLE
这是没做兼容IE吗

### ISSUE THREAD

**Issue by zhangxuanlin** [javaLuo/react-vcode#5]
你这是没有兼容IE11的吗？
ie 对象不支持“assign”属性或方法

**Comment by javaLuo** [comment]
额..是的，疏忽了IE 抱歉。 
我现在加上了Object.assign polify
但我可能需要明天才能测试，我现在没有windows系统

**Comment by zhangxuanlin** [comment]
哈哈，好的，你不改我都想改你源码了

**Comment by javaLuo** [comment]
Hi, 我重新发了一版。
1. 用了es6-object-assign
2. 其他依赖包都升级到了最新版本

我不是很确定，我自己测试时不加polify，IE中也能正常运行。
可能是因为有babel-preset-env的缘故

**Comment by zhangxuanlin** [comment]
昨天你版本更新我重新install，测试可以了，点赞
