### ISSUE TITLE
第一次生成的验证码，怎么获取到？

### ISSUE THREAD

**Issue by freshmilk15** [javaLuo/react-vcode#7]

**Comment by javaLuo** [comment]
第1次加载，onChange也会触发一次

**Comment by freshmilk15** [comment]
嗯，谢谢回复
我这里怎么总是第一次不成功呢，非要点击刷新一次，我试试吧，看看是不是别的代码的问题，谢谢




------------------ 原始邮件 ------------------
发件人: "Logic"<notifications@github.com>; 
发送时间: 2019年7月4日(星期四) 下午4:04
收件人: "javaLuo/react-vcode"<react-vcode@noreply.github.com>; 
抄送: "李小廷"<707199408@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [javaLuo/react-vcode] 第一次生成的验证码，怎么获取到？ (#7)




第1次加载，onChange也会触发一次
